IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'service' AND COLUMN_NAME = 'isChildService')
  BEGIN
    ALTER TABLE service
    ADD isChildService BIT DEFAULT 0 NOT NULL
  END
GO
