IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'service' AND COLUMN_NAME = 'isHiddenService')
  BEGIN
    ALTER TABLE service
    ADD isHiddenService BIT DEFAULT 0 NOT NULL
  END
GO
